Add eth connector
Near-One/rainbow-bridge-sdk-rs pull request #5
Opened 2024-06-21 14:32 UTC by kiseln

# Overview
Added eth-connector integration. Confirmed it works on testnet.

Refactored error types. Made sure errors are grouped together by the underlying cause. For example, if proof generation fails because RPC is unavailable it will be converted to `EthRpcError`. In other cases it will map to an `EthProofError`

# TODO/ideas
- Add a macro for generic getters like this 
```
    fn eth_endpoint(&self) -> Result<&str> {
        Ok(self.eth_endpoint
            .as_ref()
            .ok_or(BridgeSdkError::ConfigError("Ethereum rpc endpoint is not set".to_string()))?)
    }
```
- Complete bridge cli for nep141-connector. Split command arguments. Currently arguments only relevant for `nep141-connector` are showing in the hints for `eth-connector` and vice-versa

2024-06-25 14:14 UTC, karim-en requested changes
Please apply cargo fmt

2024-06-25 14:35 UTC, kiseln commented
> Please apply cargo fmt

Done

2024-06-27 13:46 UTC, kiseln commented on bridge-cli/src/main.rs
> +                EthConnectorSubCommand::FinalizeWithdraw { reciept_id, config_cli } => {
On Ethereum it will not be sent, on Near it will

2024-06-27 13:52 UTC, kiseln commented on bridge-cli/src/main.rs
> +                EthConnectorSubCommand::FinalizeDeposit { tx_hash, log_index, config_cli } => {
Can add in the following PR for both connectors

2024-06-27 14:44 UTC, karim-en approved these changes

2024-06-27 14:45 UTC, merged